import { RouteType, TrainColor } from './models';
import type { City, Route } from './models';

export const cities: Record<string, City> = {
    'london': { id: 'london', name: 'London', x: 200, y: 200 },
    'edinburgh': { id: 'edinburgh', name: 'Edinburgh', x: 180, y: 100 },
    'paris': { id: 'paris', name: 'Paris', x: 250, y: 350 },
    'madrid': { id: 'madrid', name: 'Madrid', x: 100, y: 550 },
    'lisbon': { id: 'lisbon', name: 'Lisbon', x: 40, y: 580 },
    'barcelona': { id: 'barcelona', name: 'Barcelona', x: 220, y: 560 },
    'marseille': { id: 'marseille', name: 'Marseille', x: 300, y: 480 },
    'roma': { id: 'roma', name: 'Roma', x: 450, y: 580 },
    'napoli': { id: 'napoli', name: 'Napoli', x: 500, y: 650 },
    'palermo': { id: 'palermo', name: 'Palermo', x: 460, y: 750 },
    'zurich': { id: 'zurich', name: 'Zürich', x: 350, y: 400 },
    'venezia': { id: 'venezia', name: 'Venezia', x: 420, y: 460 },
    'munchen': { id: 'munchen', name: 'München', x: 420, y: 360 },
    'frankfurt': { id: 'frankfurt', name: 'Frankfurt', x: 350, y: 280 },
    'amsterdam': { id: 'amsterdam', name: 'Amsterdam', x: 300, y: 180 },
    'brussels': { id: 'brussels', name: 'Brussels', x: 280, y: 250 },
    'berlin': { id: 'berlin', name: 'Berlin', x: 500, y: 180 },
    'wien': { id: 'wien', name: 'Wien', x: 520, y: 350 },
    'budapest': { id: 'budapest', name: 'Budapest', x: 600, y: 380 },
    'zagreb': { id: 'zagreb', name: 'Zagreb', x: 530, y: 450 },
    'sarajevo': { id: 'sarajevo', name: 'Sarajevo', x: 580, y: 510 },
    'athina': { id: 'athina', name: 'Athina', x: 650, y: 680 },
    'sofia': { id: 'sofia', name: 'Sofia', x: 660, y: 520 },
    'bucuresti': { id: 'bucuresti', name: 'Bucuresti', x: 750, y: 450 },
    'kyiv': { id: 'kyiv', name: 'Kyiv', x: 800, y: 250 },
    'warszawa': { id: 'warszawa', name: 'Warszawa', x: 620, y: 200 },
    'moskva': { id: 'moskva', name: 'Moskva', x: 950, y: 100 },
    'stockholm': { id: 'stockholm', name: 'Stockholm', x: 550, y: 50 },
    'copenhagen': { id: 'copenhagen', name: 'København', x: 450, y: 100 }
};

export const initialRoutes: Route[] = [
    { id: 'lon-edi-1', from: 'london', to: 'edinburgh', color: TrainColor.black, length: 4, type: RouteType.normal },
    { id: 'lon-edi-2', from: 'london', to: 'edinburgh', color: TrainColor.orange, length: 4, type: RouteType.normal },
    { id: 'lon-ams', from: 'london', to: 'amsterdam', color: TrainColor.any, length: 2, type: RouteType.ferry, locomotivesRequired: 2 },
    { id: 'lon-die', from: 'london', to: 'paris', color: TrainColor.any, length: 2, type: RouteType.ferry, locomotivesRequired: 1 }, // simplified London to Paris ferry
    { id: 'par-bru-1', from: 'paris', to: 'brussels', color: TrainColor.yellow, length: 2, type: RouteType.normal },
    { id: 'par-bru-2', from: 'paris', to: 'brussels', color: TrainColor.red, length: 2, type: RouteType.normal },
    { id: 'par-mad', from: 'paris', to: 'madrid', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'par-mar', from: 'paris', to: 'marseille', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'par-zur', from: 'paris', to: 'zurich', color: TrainColor.any, length: 3, type: RouteType.tunnel },
    { id: 'mad-lis', from: 'madrid', to: 'lisbon', color: TrainColor.pink, length: 3, type: RouteType.normal },
    { id: 'mad-bar', from: 'madrid', to: 'barcelona', color: TrainColor.yellow, length: 2, type: RouteType.normal },
    { id: 'bar-mar', from: 'barcelona', to: 'marseille', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'mar-rom', from: 'marseille', to: 'roma', color: TrainColor.any, length: 4, type: RouteType.tunnel },
    { id: 'mar-zur', from: 'marseille', to: 'zurich', color: TrainColor.pink, length: 2, type: RouteType.tunnel },
    { id: 'rom-nap', from: 'roma', to: 'napoli', color: TrainColor.white, length: 2, type: RouteType.normal },
    { id: 'nap-pal', from: 'napoli', to: 'palermo', color: TrainColor.any, length: 3, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'zur-ven', from: 'zurich', to: 'venezia', color: TrainColor.green, length: 2, type: RouteType.tunnel },
    { id: 'zur-mun', from: 'zurich', to: 'munchen', color: TrainColor.yellow, length: 2, type: RouteType.tunnel },
    { id: 'mun-ven', from: 'munchen', to: 'venezia', color: TrainColor.blue, length: 2, type: RouteType.tunnel },
    { id: 'ven-rom', from: 'venezia', to: 'roma', color: TrainColor.black, length: 4, type: RouteType.normal },
    { id: 'ams-bru', from: 'amsterdam', to: 'brussels', color: TrainColor.black, length: 1, type: RouteType.normal },
    { id: 'ams-fra', from: 'amsterdam', to: 'frankfurt', color: TrainColor.white, length: 2, type: RouteType.normal },
    { id: 'bru-fra', from: 'brussels', to: 'frankfurt', color: TrainColor.blue, length: 2, type: RouteType.normal },
    { id: 'fra-mun', from: 'frankfurt', to: 'munchen', color: TrainColor.pink, length: 2, type: RouteType.normal },
    { id: 'fra-ber-1', from: 'frankfurt', to: 'berlin', color: TrainColor.red, length: 3, type: RouteType.normal },
    { id: 'fra-ber-2', from: 'frankfurt', to: 'berlin', color: TrainColor.black, length: 3, type: RouteType.normal },
    { id: 'mun-wie', from: 'munchen', to: 'wien', color: TrainColor.orange, length: 3, type: RouteType.normal },
    { id: 'wie-bud-1', from: 'wien', to: 'budapest', color: TrainColor.red, length: 1, type: RouteType.normal },
    { id: 'wie-bud-2', from: 'wien', to: 'budapest', color: TrainColor.white, length: 1, type: RouteType.normal },
    { id: 'wie-zag', from: 'wien', to: 'zagreb', color: TrainColor.any, length: 2, type: RouteType.normal },
    { id: 'ven-zag', from: 'venezia', to: 'zagreb', color: TrainColor.any, length: 2, type: RouteType.normal },
    { id: 'zag-sar', from: 'zagreb', to: 'sarajevo', color: TrainColor.red, length: 3, type: RouteType.normal },
    { id: 'zag-bud', from: 'zagreb', to: 'budapest', color: TrainColor.orange, length: 2, type: RouteType.normal },
    { id: 'sar-ath', from: 'sarajevo', to: 'athina', color: TrainColor.green, length: 4, type: RouteType.normal },
    { id: 'sar-sof', from: 'sarajevo', to: 'sofia', color: TrainColor.any, length: 2, type: RouteType.normal },
    { id: 'sof-ath', from: 'sofia', to: 'athina', color: TrainColor.pink, length: 3, type: RouteType.normal },
    { id: 'sof-buc', from: 'sofia', to: 'bucuresti', color: TrainColor.any, length: 2, type: RouteType.tunnel },
    { id: 'buc-bud', from: 'bucuresti', to: 'budapest', color: TrainColor.any, length: 4, type: RouteType.tunnel },
    { id: 'buc-kyi', from: 'bucuresti', to: 'kyiv', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'bud-kyi', from: 'budapest', to: 'kyiv', color: TrainColor.any, length: 6, type: RouteType.tunnel },
    { id: 'wie-war', from: 'wien', to: 'warszawa', color: TrainColor.blue, length: 4, type: RouteType.normal },
    { id: 'ber-war', from: 'berlin', to: 'warszawa', color: TrainColor.pink, length: 4, type: RouteType.normal },
    { id: 'ber-cop', from: 'berlin', to: 'copenhagen', color: TrainColor.any, length: 3, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'cop-sto', from: 'copenhagen', to: 'stockholm', color: TrainColor.yellow, length: 3, type: RouteType.normal },
    { id: 'war-kyi', from: 'warszawa', to: 'kyiv', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'war-mos', from: 'warszawa', to: 'moskva', color: TrainColor.any, length: 6, type: RouteType.normal },
    { id: 'kyi-mos', from: 'kyiv', to: 'moskva', color: TrainColor.any, length: 4, type: RouteType.normal }
];
