import { RouteType, TrainColor } from './models';
import type { City, Route, Ticket } from './models';

export const cities: Record<string, City> = {
    'london': { id: 'london', name: 'London', x: 160, y: 210 },
    'edinburgh': { id: 'edinburgh', name: 'Edinburgh', x: 140, y: 80 },
    'paris': { id: 'paris', name: 'Paris', x: 210, y: 370 },
    'madrid': { id: 'madrid', name: 'Madrid', x: 100, y: 600 },
    'lisbon': { id: 'lisbon', name: 'Lisbon', x: 40, y: 680 },
    'barcelona': { id: 'barcelona', name: 'Barcelona', x: 220, y: 620 },
    'marseille': { id: 'marseille', name: 'Marseille', x: 290, y: 520 },
    'roma': { id: 'roma', name: 'Roma', x: 470, y: 610 },
    'napoli': { id: 'napoli', name: 'Napoli', x: 530, y: 680 },
    'palermo': { id: 'palermo', name: 'Palermo', x: 480, y: 780 },
    'zurich': { id: 'zurich', name: 'Zürich', x: 350, y: 430 },
    'venezia': { id: 'venezia', name: 'Venezia', x: 440, y: 500 },
    'munchen': { id: 'munchen', name: 'München', x: 450, y: 380 },
    'frankfurt': { id: 'frankfurt', name: 'Frankfurt', x: 370, y: 280 },
    'amsterdam': { id: 'amsterdam', name: 'Amsterdam', x: 290, y: 180 },
    'brussels': { id: 'brussels', name: 'Brussels', x: 260, y: 260 },
    'berlin': { id: 'berlin', name: 'Berlin', x: 520, y: 180 },
    'wien': { id: 'wien', name: 'Wien', x: 560, y: 360 },
    'budapest': { id: 'budapest', name: 'Budapest', x: 660, y: 390 },
    'zagreb': { id: 'zagreb', name: 'Zagreb', x: 560, y: 470 },
    'sarajevo': { id: 'sarajevo', name: 'Sarajevo', x: 610, y: 530 },
    'athina': { id: 'athina', name: 'Athina', x: 680, y: 700 },
    'sofia': { id: 'sofia', name: 'Sofia', x: 700, y: 540 },
    'bucuresti': { id: 'bucuresti', name: 'Bucuresti', x: 800, y: 460 },
    'kyiv': { id: 'kyiv', name: 'Kyiv', x: 860, y: 250 },
    'warszawa': { id: 'warszawa', name: 'Warszawa', x: 670, y: 190 },
    'moskva': { id: 'moskva', name: 'Moskva', x: 970, y: 70 },
    'stockholm': { id: 'stockholm', name: 'Stockholm', x: 580, y: 30 },
    'copenhagen': { id: 'copenhagen', name: 'København', x: 460, y: 90 },
    
    // New cities added for visual detail, island connections, and deeper route maps
    'dublin': { id: 'dublin', name: 'Dublin', x: 80, y: 160 },
    'oslo': { id: 'oslo', name: 'Oslo', x: 430, y: 60 },
    'istanbul': { id: 'istanbul', name: 'Istanbul', x: 770, y: 620 },
    'sevastopol': { id: 'sevastopol', name: 'Sevastopol', x: 900, y: 480 }
};

export const initialRoutes: Route[] = [
    { id: 'lon-edi-1', from: 'london', to: 'edinburgh', color: TrainColor.black, length: 4, type: RouteType.normal },
    { id: 'lon-edi-2', from: 'london', to: 'edinburgh', color: TrainColor.orange, length: 4, type: RouteType.normal },
    { id: 'lon-ams', from: 'london', to: 'amsterdam', color: TrainColor.any, length: 2, type: RouteType.ferry, locomotivesRequired: 2 },
    { id: 'lon-die', from: 'london', to: 'paris', color: TrainColor.any, length: 2, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'par-bru-1', from: 'paris', to: 'brussels', color: TrainColor.yellow, length: 2, type: RouteType.normal },
    { id: 'par-bru-2', from: 'paris', to: 'brussels', color: TrainColor.red, length: 2, type: RouteType.normal },
    { id: 'par-mad', from: 'paris', to: 'madrid', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'par-mar', from: 'paris', to: 'marseille', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'par-zur', from: 'paris', to: 'zurich', color: TrainColor.any, length: 3, type: RouteType.tunnel },
    { id: 'mad-lis', from: 'madrid', to: 'lisbon', color: TrainColor.pink, length: 3, type: RouteType.normal },
    { id: 'mad-bar', from: 'madrid', to: 'barcelona', color: TrainColor.yellow, length: 2, type: RouteType.normal },
    { id: 'bar-mar', from: 'barcelona', to: 'marseille', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'mar-rom', from: 'marseille', to: 'roma', color: TrainColor.any, length: 4, type: RouteType.tunnel },
    { id: 'mar-zur', from: 'marseille', to: 'zurich', color: TrainColor.pink, length: 2, type: RouteType.tunnel },
    { id: 'rom-nap', from: 'roma', to: 'napoli', color: TrainColor.white, length: 2, type: RouteType.normal },
    { id: 'nap-pal', from: 'napoli', to: 'palermo', color: TrainColor.any, length: 3, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'zur-ven', from: 'zurich', to: 'venezia', color: TrainColor.green, length: 2, type: RouteType.tunnel },
    { id: 'zur-mun', from: 'zurich', to: 'munchen', color: TrainColor.yellow, length: 2, type: RouteType.tunnel },
    { id: 'mun-ven', from: 'munchen', to: 'venezia', color: TrainColor.blue, length: 2, type: RouteType.tunnel },
    { id: 'ven-rom', from: 'venezia', to: 'roma', color: TrainColor.black, length: 4, type: RouteType.normal },
    { id: 'ams-bru', from: 'amsterdam', to: 'brussels', color: TrainColor.black, length: 1, type: RouteType.normal },
    { id: 'ams-fra', from: 'amsterdam', to: 'frankfurt', color: TrainColor.white, length: 2, type: RouteType.normal },
    { id: 'bru-fra', from: 'brussels', to: 'frankfurt', color: TrainColor.blue, length: 2, type: RouteType.normal },
    { id: 'fra-mun', from: 'frankfurt', to: 'munchen', color: TrainColor.pink, length: 2, type: RouteType.normal },
    { id: 'fra-ber-1', from: 'frankfurt', to: 'berlin', color: TrainColor.red, length: 3, type: RouteType.normal },
    { id: 'fra-ber-2', from: 'frankfurt', to: 'berlin', color: TrainColor.black, length: 3, type: RouteType.normal },
    { id: 'mun-wie', from: 'munchen', to: 'wien', color: TrainColor.orange, length: 3, type: RouteType.normal },
    { id: 'wie-bud-1', from: 'wien', to: 'budapest', color: TrainColor.red, length: 1, type: RouteType.normal },
    { id: 'wie-bud-2', from: 'wien', to: 'budapest', color: TrainColor.white, length: 1, type: RouteType.normal },
    { id: 'wie-zag', from: 'wien', to: 'zagreb', color: TrainColor.any, length: 2, type: RouteType.normal },
    { id: 'ven-zag', from: 'venezia', to: 'zagreb', color: TrainColor.any, length: 2, type: RouteType.normal },
    { id: 'zag-sar', from: 'zagreb', to: 'sarajevo', color: TrainColor.red, length: 3, type: RouteType.normal },
    { id: 'zag-bud', from: 'zagreb', to: 'budapest', color: TrainColor.orange, length: 2, type: RouteType.normal },
    { id: 'sar-ath', from: 'sarajevo', to: 'athina', color: TrainColor.green, length: 4, type: RouteType.normal },
    { id: 'sar-sof', from: 'sarajevo', to: 'sofia', color: TrainColor.any, length: 2, type: RouteType.normal },
    { id: 'sof-ath', from: 'sofia', to: 'athina', color: TrainColor.pink, length: 3, type: RouteType.normal },
    { id: 'sof-buc', from: 'sofia', to: 'bucuresti', color: TrainColor.any, length: 2, type: RouteType.tunnel },
    { id: 'buc-bud', from: 'bucuresti', to: 'budapest', color: TrainColor.any, length: 4, type: RouteType.tunnel },
    { id: 'buc-kyi', from: 'bucuresti', to: 'kyiv', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'bud-kyi', from: 'budapest', to: 'kyiv', color: TrainColor.any, length: 6, type: RouteType.tunnel },
    { id: 'wie-war', from: 'wien', to: 'warszawa', color: TrainColor.blue, length: 4, type: RouteType.normal },
    { id: 'ber-war', from: 'berlin', to: 'warszawa', color: TrainColor.pink, length: 4, type: RouteType.normal },
    { id: 'ber-cop', from: 'berlin', to: 'copenhagen', color: TrainColor.any, length: 3, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'cop-sto', from: 'copenhagen', to: 'stockholm', color: TrainColor.any, length: 3, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'bar-pal', from: 'barcelona', to: 'palermo', color: TrainColor.any, length: 5, type: RouteType.ferry, locomotivesRequired: 2 },
    { id: 'pal-ath', from: 'palermo', to: 'athina', color: TrainColor.any, length: 4, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'sto-war', from: 'stockholm', to: 'warszawa', color: TrainColor.any, length: 4, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'war-kyi', from: 'warszawa', to: 'kyiv', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'war-mos', from: 'warszawa', to: 'moskva', color: TrainColor.any, length: 6, type: RouteType.normal },
    { id: 'kyi-mos', from: 'kyiv', to: 'moskva', color: TrainColor.any, length: 4, type: RouteType.normal },

    // New island / ferry and overland routes for the expanded board
    { id: 'dub-lon', from: 'dublin', to: 'london', color: TrainColor.any, length: 3, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'edi-osl', from: 'edinburgh', to: 'oslo', color: TrainColor.any, length: 4, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'osl-sto', from: 'oslo', to: 'stockholm', color: TrainColor.any, length: 3, type: RouteType.normal },
    { id: 'osl-cop', from: 'oslo', to: 'copenhagen', color: TrainColor.any, length: 2, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'ist-sof', from: 'istanbul', to: 'sofia', color: TrainColor.any, length: 2, type: RouteType.normal },
    { id: 'ist-ath', from: 'istanbul', to: 'athina', color: TrainColor.any, length: 2, type: RouteType.ferry, locomotivesRequired: 1 },
    { id: 'sev-buc', from: 'sevastopol', to: 'bucuresti', color: TrainColor.any, length: 4, type: RouteType.normal },
    { id: 'sev-kyi', from: 'sevastopol', to: 'kyiv', color: TrainColor.any, length: 4, type: RouteType.normal }
];

export const initialTickets: Ticket[] = [
    { id: 't1', from: 'london', to: 'moskva', points: 20 },
    { id: 't2', from: 'paris', to: 'athina', points: 12 },
    { id: 't3', from: 'edinburgh', to: 'wien', points: 11 },
    { id: 't4', from: 'lisbon', to: 'warszawa', points: 18 },
    { id: 't5', from: 'madrid', to: 'kyiv', points: 17 },
    { id: 't6', from: 'dublin', to: 'berlin', points: 13 },
    { id: 't7', from: 'oslo', to: 'roma', points: 15 },
    { id: 't8', from: 'palermo', to: 'stockholm', points: 18 },
    { id: 't9', from: 'marseille', to: 'istanbul', points: 16 },
    { id: 't10', from: 'london', to: 'sevastopol', points: 17 },
    { id: 't11', from: 'amsterdam', to: 'athina', points: 12 },
    { id: 't12', from: 'berlin', to: 'bucuresti', points: 8 },
    { id: 't13', from: 'brussels', to: 'warszawa', points: 7 },
    { id: 't14', from: 'copenhagen', to: 'sarajevo', points: 10 },
    { id: 't15', from: 'frankfurt', to: 'roma', points: 8 },
    { id: 't16', from: 'kyiv', to: 'venezia', points: 9 },
    { id: 't17', from: 'madrid', to: 'marseille', points: 5 },
    { id: 't18', from: 'munchen', to: 'budapest', points: 5 },
    { id: 't19', from: 'napoli', to: 'frankfurt', points: 7 },
    { id: 't20', from: 'paris', to: 'zagreb', points: 7 },
    { id: 't21', from: 'roma', to: 'sofia', points: 6 },
    { id: 't22', from: 'warszawa', to: 'budapest', points: 5 },
    { id: 't23', from: 'wien', to: 'sarajevo', points: 4 },
    { id: 't24', from: 'zurich', to: 'copenhagen', points: 6 },
    { id: 't25', from: 'barcelona', to: 'brussels', points: 8 },
    { id: 't26', from: 'edinburgh', to: 'paris', points: 7 },
    { id: 't27', from: 'lisbon', to: 'barcelona', points: 5 },
    { id: 't28', from: 'oslo', to: 'stockholm', points: 4 },
    { id: 't29', from: 'istanbul', to: 'athina', points: 5 },
    { id: 't30', from: 'sevastopol', to: 'moskva', points: 6 }
];
